version: '2'

services:
  db:
    restart: always
    image: mongo:3.2.3
    volumes:
      - leanote_data:/data/db
  server:
    environment:
      - SITE_URL="http://0.0.0.0:9000"
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - 9000:9000
    tty: true
    links:
      - db:mongodb
volumes:
      leanote_data:
